<?php

declare(strict_types=1);

namespace voku\AgentLoop\Init;

use InvalidArgumentException;
use RuntimeException;
use voku\AgentLoop\GitWorkTree;

/** Applies only the repository-declared local Git integration. */
final readonly class RepositoryGitIntegrationSynchronizer
{
    /** @var list<string> */
    private const array HOOK_ENTRIES = [
        'agent-map-refresh.sh',
        'commit-msg',
        'lib/agent-loop-hooks.sh',
        'post-checkout',
        'post-merge',
        'pre-commit',
    ];

    /** @var list<string> */
    private const array EXECUTABLE_ENTRIES = [
        'agent-map-refresh.sh',
        'commit-msg',
        'post-checkout',
        'post-merge',
        'pre-commit',
    ];

    private const string ENV_ENTRY = 'lib/agent-loop-hooks.env';

    public function __construct(private string $rootPath)
    {
    }

    public function syncDeclared(): void
    {
        $activation = new RepositoryActivation($this->rootPath);
        if (!$activation->declaresGitHookPolicy()) {
            throw new InvalidArgumentException('Repository does not declare a local Git hook policy.');
        }

        $sourceRoot = dirname(__DIR__, 2) . '/githooks';
        if (!is_dir($sourceRoot)) {
            throw new RuntimeException('Bundled githooks root is missing: ' . $sourceRoot);
        }

        $hooksDir = $activation->gitHooksDirectory();
        $targetRoot = $this->rootPath . '/' . $hooksDir;
        $manifest = InitSyncManifest::load($targetRoot, 'githooks', 'git');
        $desiredEntries = [...self::HOOK_ENTRIES, self::ENV_ENTRY];
        sort($desiredEntries, SORT_STRING);

        $adoptExisting = is_file($targetRoot . '/lib/agent-loop-hooks.sh')
            && !is_file($targetRoot . '/' . InitSyncManifest::fileName());
        $adopted = [];
        foreach ($desiredEntries as $entry) {
            $targetPath = $targetRoot . '/' . $entry;
            if (!is_file($targetPath) || $manifest->isManaged($entry)) {
                continue;
            }
            if (!$adoptExisting) {
                throw new InvalidArgumentException(
                    'Unmanaged Git integration target already exists: ' . $targetPath,
                );
            }
            $adopted[$entry] = true;
        }

        foreach ($manifest->staleEntries($desiredEntries) as $staleEntry) {
            $targetPath = $targetRoot . '/' . $staleEntry;
            if (is_file($targetPath) && !unlink($targetPath)) {
                throw new RuntimeException('Unable to remove stale hook: ' . $targetPath);
            }
        }

        foreach (self::HOOK_ENTRIES as $entry) {
            $targetPath = $targetRoot . '/' . $entry;
            if (isset($adopted[$entry])) {
                if (in_array($entry, self::EXECUTABLE_ENTRIES, true)
                    && !is_executable($targetPath)
                    && !chmod($targetPath, 0o755)
                ) {
                    throw new RuntimeException('Unable to make adopted Git hook executable: ' . $targetPath);
                }
                continue;
            }

            $content = file_get_contents($sourceRoot . '/' . $entry);
            if (!is_string($content)) {
                throw new RuntimeException('Unable to read bundled hook: ' . $sourceRoot . '/' . $entry);
            }
            $this->writeFile($targetPath, $content);
            if (in_array($entry, self::EXECUTABLE_ENTRIES, true) && !chmod($targetPath, 0o755)) {
                throw new RuntimeException('Unable to make Git hook executable: ' . $targetPath);
            }
        }

        if (!isset($adopted[self::ENV_ENTRY])) {
            $this->writeFile(
                $targetRoot . '/' . self::ENV_ENTRY,
                "# Generated by agent-loop repository setup.\n"
                . 'AGENT_LOOP_BIN=' . escapeshellarg($activation->cliPath()) . "\n",
            );
        }

        $manifest->write($desiredEntries);
        $this->applyGitConfiguration($activation, $hooksDir);
    }

    private function applyGitConfiguration(RepositoryActivation $activation, string $hooksDir): void
    {
        if (!GitWorkTree::detected($this->rootPath)) {
            return;
        }

        $settings = ['core.hooksPath' => $hooksDir];
        if ($activation->declaresCommitTemplate()) {
            $template = '.gitmessage';
            if (!is_file($this->rootPath . '/' . $template)) {
                throw new RuntimeException('Declared commit template is missing: ' . $template);
            }
            $settings['commit.template'] = $template;
        }

        foreach ($settings as $key => $value) {
            $command = 'git -C ' . escapeshellarg($this->rootPath)
                . ' config ' . escapeshellarg($key) . ' ' . escapeshellarg($value);
            exec($command, $output, $exitCode);
            if ($exitCode !== 0) {
                throw new RuntimeException('Unable to set ' . $key . ' in the repository-local Git configuration.');
            }
        }
    }

    private function writeFile(string $path, string $content): void
    {
        $directory = dirname($path);
        if (!is_dir($directory) && !mkdir($directory, 0o775, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create Git integration directory: ' . $directory);
        }
        if (file_put_contents($path, $content) === false) {
            throw new RuntimeException('Unable to write Git integration file: ' . $path);
        }
    }
}
